### ISSUE TITLE
TP : remarques sur la comparaison entre DuckDB et Arrow

### ISSUE THREAD

**Issue by ericemc3** [InseeFrLab/formation-bceao#8]
J'ai étudié le TP "Manipulation de données massives" avec beaucoup d'intérêt, appréciant les différents environnements testés et le fait qu'un fichier de taille substantielle (RP17) soit convoqué pour asseoir les comparaisons.

La requête DuckDB de la partie 3 pourrait être écrite de façon plus lisible, plus élégante, tout en prenant en compte l'ensemble du process d'acquisition des données.
Au passage, pour mettre à jour ce que le doc affirme, DuckDB lit bien les partitions parquet depuis la mi 2022.
```
library(duckdb)

con <- dbConnect(duckdb())
DBI::dbExecute(con, "LOAD httpfs; SET threads = 6")

t <- Sys.time()

query_sql <- "
WITH t1 as(
  SELECT COMMUNE,
       COUNT(*) FILTER (WHERE TYPL = '5') AS nb_logements_fortune,
       COUNT(*) AS nb_logements_commune,
       nb_logements_fortune / nb_logements_commune AS part_logements_fortune
       FROM read_parquet('data/data_partition/*/*.parquet', hive_partitioning = 1)
       GROUP BY ALL
)
SELECT
      tc.Département, t1.*
      FROM t1
      LEFT JOIN (select Département, \"Code INSEE\" as codgeo 
                 from 'https://minio.lab.sspcloud.fr/projet-formation/diffusion/bceao/table_communes.parquet') tc
      ON t1.COMMUNE = tc.codgeo
      ORDER BY part_logements_fortune DESC ;"
  
DBI::dbGetQuery(con, query_sql) |> as_tibble()

elapsed_duckdb_sql <- as.numeric(difftime(Sys.time(), t, units = "secs"))
```
Sur Onyxia/sspcloud je mesure 1,3 s.

Et il me parait plus juste de considérer, pour la comparaison avec arrow, toute cette séquence :

```
library(tidyverse)

t <- Sys.time()

data_lazy <- arrow::open_dataset(
  source = "data/data_partition",
  partitioning = arrow::schema(REGION = arrow::utf8()))

# table de correspondance au format parquet
table_communes <- arrow::read_parquet('https://minio.lab.sspcloud.fr/projet-formation/diffusion/bceao/table_communes.parquet')

data_lazy |> 
  select(REGION, COMMUNE, TYPL) |> 
  group_by(COMMUNE) |>
  summarise(
    nb_logements_fortune = sum(TYPL %in% "5"),
    nb_logements_commune = n()
  ) |>
  mutate(
    part_logements_fortune = nb_logements_fortune / nb_logements_commune
  ) |> 
  left_join(table_communes, by=c("COMMUNE"="Code INSEE")) |>
  select(Commune, Département, nb_logements_fortune, nb_logements_commune, part_logements_fortune) |>
  arrange(-part_logements_fortune)  |> 
  collect()

elapsed_lazy <- as.numeric(difftime(Sys.time(), t, units = "secs"))
```
 Sur Onyxia je mesure 2,1 s.

Les 4 cas d'usage considérés m'amènent à ce graphique : 

![image](https://github.com/InseeFrLab/formation-bceao/assets/17407796/2799d6dc-082d-4584-b5ac-2c8572129d1f)

**Comment by ThomasFaria** [comment]
Bonjour @ericemc3, merci beaucoup pour ces retours très appréciables !
Je me charge de les intégrer dès que possible dans le TP ! La version de Quarto utilisée est la même que celle présente par défaut sur les services interactifs du SSP Cloud, à savoir la dernière version stable (1.3.450 à ce jour), préfères tu qu'on y installe la dernière pre-release ?

Si tu as d'autres remarques n'hésite pas à nous en faire part, ou même si tu as des idées de contributions tu peux trouver le code source du tp ici pour faire une PR : https://github.com/InseeFrLab/formation-bceao/blob/main/tp/tp-manip-donnees-massives-fr.qmd

**Comment by ericemc3** [comment]
Bonjour @ThomasFaria, et merci pour ta réponse et ton ouverture, ainsi que le lien vers le TP d'origine.
Si la version de Quarto installée est la dernière stable, c'est très bien. Il faudra que je vérifie quelle version de Plot elle embarque.

**Comment by ThomasFaria** [comment]
Bonjour @ericemc3 , 
J'ai pris en compte tes changements merci encore ! De manière étonnante j'obtiens "arrow lazy" en plus rapide, alors que de mémoire c'était plutôt DuckDB comme sur ton image. J'inspecterai ça plus en détail prochainement.

**Comment by ericemc3** [comment]
Bonjour @ThomasFaria, et merci pour la note et cette prise en compte. Dans mon souvenir, un petit `SET THREADS = 6` avait sensiblement amélioré encore la vitesse de DuckDB. Par défaut, ce paramètre équivaut au nombre de cœurs de la machine, mais l'expérience montre que le réduire, pour certaines requêtes lourdes, a un effet positif. C'est une histoire d'optimisation de l'algorithme de parallèlisation. J'imagine et j'espère que cela deviendra plus transparent.

En regardant de plus près :
`SELECT * FROM duckdb_settings() where name='threads'`
donne dans l'environnement Onyxia 30, ce qui est pas mal (sur mon PC, j'ai 12). 
On a alors une exécution qui prend autour de 1,4 s.

Avec  SET THREADS = 6, je tombe à 0.9 s

Enfin, pour bien aligner la comparaison avec Arrow, il convient de rajouter au début de la séquence arrow lazy cette opération de chargement de la table des communes, et en https comme pour duckdb (sachant que duckdb peut normalement lire du s3, mais il faut lui donner toutes les infos d'authentification ou faire avant un `CALL load_aws_credentials()`) :
```
table_communes <- arrow::read_parquet(
  file = 'https://minio.lab.sspcloud.fr/projet-formation/diffusion/bceao/table_communes.parquet'
)
```
Pour arrow lazy je mesure 1,5 s, toujours sur l'environnement Onyxia.
